// <auto-generated />
using ADO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ADO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Modelo.Alumno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ex_12FactApp_12PTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ex_ADOO_8PTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ex_Docker_5PTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ex_GIT_6PTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ex_SOLID_8PTS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ex_ScrumTra_41PTS")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
